### PR TITLE
Add centralized docker-compose files

### PR DESCRIPTION
**Pull request by lazyguru**
- Moves "seeder" to centralized docker repo
- Remove docker-compose.dev.yml file in favor of centralized one
- Update package.json script for running docker to point at correct file
- Update README to add instructions for updating submodules as well as clean up some formatting

### CODE REVIEW

**Review by kgilles — COMMENTED** [review]
This is a great setup and it works if I use the amd64 platforms for the Sublinks images.

However, my M1 Mac fails to start the federation service using the arm64 image.
Giving me [this error](https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc). Any chance you're familiar with this and know a way around it that doesn't require arm64 systems to force set a different platform?

**Comment by lazyguru** [comment]
Oh... I think I can see how to solve for that. I'll work on that this week

**Comment by lazyguru** [comment]
@kgilles please try again. It should be fixed now

**Comment by lazyguru** [comment]
@sublinks/sublinks-frontend-service @kgilles this should be ready for final review now

**Comment by lazyguru** [comment]
Oooh, one more update. Dependabot should take care of future updates to the submodule for you now 😄

**Review by kgilles — APPROVED** [review]
Great stuff! It works nicely now.

I added some minor updates to the readme

**Pull request merged**
